### ISSUE TITLE
Farbgestaltung dark-mode

### ISSUE THREAD

**Issue by berecont** [do-while/contao-ce_be_remarks#1]
Contao 5.3.11

Im `dark-mode` ist die Notiz nicht lesbar »
```
html[data-color-scheme="dark"] .ce_be_remarks {
    background-color: #2d333b;
}
```

**Comment by do-while** [comment]
Danke für den Hinweis. Den Darkmodus kennt das Modul noch nicht, ich trage das nach.

**Comment by do-while** [comment]
Danke für die schnelle Lösung, ich habe es gleich in Version 2.0.1 veröffentlicht
